MODEA EQU 0X01
    ORG 0X00
    GOTO INICIO
    
    ORG 0X04
INT
	NOP
	NOP
	NOP
	GOTO INT
INICIO
    BSF STATUS, RP0
    CLRF TRISB
    BCF STATUS, RP0
LOOP
    MOVLW 0x3F 
    MOVWF PORTB
    MOVLW 0x06
    MOVWF PORTB
    MOVLW 0x5B
    MOVWF PORTB
    MOVLW 0x4F
    MOVWF PORTB
    MOVLW 0x66
    MOVWF PORTB
    MOVLW 0x6D
    MOVWF PORTB
    MOVLW 0x7D
    MOVWF PORTB
    MOVLW 0x07
    MOVWF PORTB
    MOVLW 0x7F
    MOVWF PORTB
    MOVLW 0x6F
    MOVWF PORTB
    MOVLW 0x77
    MOVWF PORTB
    MOVLW 0x7C
    MOVWF PORTB
    MOVLW 0x39
    MOVWF PORTB
    MOVLW 0x5E
    MOVWF PORTB
    MOVLW 0x79
    MOVWF PORTB
    MOVLW 0x71
    MOVWF PORTB
    GOTO LOOP